name: Deploy Static HTML

on:
  push:
    branches:
      - main  # Branche principale où se trouve votre code source

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Étape 3 : Construire le site Hugo
      - name: Build Hugo Site
        run: hugo --minify

      # Étape 4 : Préparer les fichiers pour GitHub Pages
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  pages:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      # Étape 5 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
