name: Deploy Static HTML

on:
  push:
    branches:
      - main  # Branche principale où se trouve votre code source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Étape 3 : Construire le site Hugo
      - name: Build Hugo Site
        run: hugo --minify

      # Étape 4 : Déployer les fichiers statiques
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

