name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # Branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Étape 3 : Installer les modules de thème (si votre projet utilise des sous-modules Git)
      - name: Install Theme Submodules
        run: git submodule update --init --recursive

      # Étape 4 : Construire le site Hugo
      - name: Build Hugo Site
        run: hugo --minify

      # Étape 5 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
